optimizer: {
  type: AdamW,
  kwargs: {
  lr: 0.001,
  weight_decay: 0.05}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 400,
    initial_epochs: 10}}

dataset: {
  train: { _base_: cfgs/dataset/ModelNet40_SVM.yaml,
            others: {partition: 'train', num_points: 1024}},
  val: { _base_: cfgs/dataset/ModelNet40_SVM.yaml,
            others: {partition: 'test', num_points: 1024}},
  test: { _base_: cfgs/dataset/ModelNet40_SVM.yaml,
            others: {partition: 'test', num_points: 1024}}}

model: {
  NAME: Point_M2AE,
  mask_ratio: 0.8,
  # tokenizers
  group_sizes: [16, 8, 8], 
  num_groups: [512, 256, 64],
  # hierarchical encoder
  encoder_depths: [5, 5, 5],
  encoder_dims: [96, 192, 384],
  local_radius: [0.32, 0.64, 1.28],  # disabled for pre-training
  # hierarchical decoder
  decoder_depths: [1, 1],
  decoder_dims: [384, 192],
  decoder_up_blocks: [1, 1],
  # others
  drop_path_rate: 0.1,
  num_heads: 6,}

total_bs: 128
step_per_update: 1
max_epoch: 300